In [1]:
from pandas import read_csv

In [2]:
df = read_csv('data/herostats.csv')

Check top 5 rows of data downloaded from https://api.opendota.com/api/heroStats
If you are interested in how this data was downloaded, see the *get_herostats* notebook: https://github.com/proafxin/dotastats/blob/main/get_herostats.ipynb

In [3]:
df.head()

,id,name,localized_name,primary_attr,attack_type,roles,img,icon,base_health,base_health_regen,...,5_pick,5_win,6_pick,6_win,7_pick,7_win,8_pick,8_win,null_pick,null_win
0,1,npc_dota_hero_antimage,Anti-Mage,agi,Melee,"['Carry', 'Escape', 'Nuker']",/apps/dota2/images/heroes/antimage_full.png?,/apps/dota2/images/heroes/antimage_icon.png,200,0.25,...,44267,22427,20511,10160,8648,4249,2008,961,2373492,0
1,2,npc_dota_hero_axe,Axe,str,Melee,"['Initiator', 'Durable', 'Disabler', 'Jungler']",/apps/dota2/images/heroes/axe_full.png?,/apps/dota2/images/heroes/axe_icon.png,200,2.75,...,34984,17649,15361,7709,5965,2897,1211,591,1879817,0
2,3,npc_dota_hero_bane,Bane,int,Ranged,"['Support', 'Disabler', 'Nuker', 'Durable']",/apps/dota2/images/heroes/bane_full.png?,/apps/dota2/images/heroes/bane_icon.png,200,NaN,...,12075,6181,6405,3362,3320,1678,1301,710,582540,0
3,4,npc_dota_hero_bloodseeker,Bloodseeker,agi,Melee,"['Carry', 'Disabler', 'Jungler', 'Nuker', 'Ini...",/apps/dota2/images/heroes/bloodseeker_full.png?,/apps/dota2/images/heroes/bloodseeker_icon.png,200,NaN,...,10537,5306,4572,2391,1815,919,422,214,868426,0
4,5,npc_dota_hero_crystal_maiden,Crystal Maiden,int,Ranged,"['Support', 'Disabler', 'Nuker', 'Jungler']",/apps/dota2/images/heroes/crystal_maiden_full....,/apps/dota2/images/heroes/crystal_maiden_icon.png,200,NaN,...,40881,20798,18614,9490,7608,3851,2117,1043,2175703,0

Check columns in this data.

In [4]:
df.columns.tolist()

['id',
 'name',
 'localized_name',
 'primary_attr',
 'attack_type',
 'roles',
 'img',
 'icon',
 'base_health',
 'base_health_regen',
 'base_mana',
 'base_mana_regen',
 'base_armor',
 'base_mr',
 'base_attack_min',
 'base_attack_max',
 'base_str',
 'base_agi',
 'base_int',
 'str_gain',
 'agi_gain',
 'int_gain',
 'attack_range',
 'projectile_speed',
 'attack_rate',
 'move_speed',
 'turn_rate',
 'cm_enabled',
 'legs',
 'hero_id',
 'turbo_picks',
 'turbo_wins',
 'pro_ban',
 'pro_win',
 'pro_pick',
 '1_pick',
 '1_win',
 '2_pick',
 '2_win',
 '3_pick',
 '3_win',
 '4_pick',
 '4_win',
 '5_pick',
 '5_win',
 '6_pick',
 '6_win',
 '7_pick',
 '7_win',
 '8_pick',
 '8_win',
 'null_pick',
 'null_win']

Drop the columns we don't need for pick/win rate. We will also drop the columns *null_pick* and *null_win* since we don't know what those numbers denote (nothing is stated about it in the documentation here: https://docs.opendota.com/#tag/hero-stats
I already ran the whole thing with these numbers included. The result seemed to make a lot less sense.

In [5]:
df = df.drop(
    [
        'id',
        'name',
        'primary_attr',
        'attack_type',
        'img',
        'icon',
        'base_health',
        'base_health_regen',
        'base_mana',
        'base_mana_regen',
        'base_armor',
        'base_mr',
        'base_attack_min',
        'base_attack_max',
        'base_str',
        'base_agi',
        'base_int',
        'str_gain',
        'agi_gain',
        'int_gain',
        'attack_range',
        'projectile_speed',
        'attack_rate',
        'move_speed',
        'turn_rate',
        'cm_enabled',
        'legs',
        'turbo_picks',
        'turbo_wins',
        #'hero_id',
        'null_pick',
        'null_win',
    ],
    axis=1,
)

In [6]:
df.head()

,localized_name,roles,hero_id,pro_ban,pro_win,pro_pick,1_pick,1_win,2_pick,2_win,...,4_pick,4_win,5_pick,5_win,6_pick,6_win,7_pick,7_win,8_pick,8_win
0,Anti-Mage,"['Carry', 'Escape', 'Nuker']",1,429,56,115,19859,9964,44853,22780,...,66175,33598,44267,22427,20511,10160,8648,4249,2008,961
1,Axe,"['Initiator', 'Durable', 'Disabler', 'Jungler']",2,53,27,84,18628,9691,41356,21099,...,54701,27801,34984,17649,15361,7709,5965,2897,1211,591
2,Bane,"['Support', 'Disabler', 'Nuker', 'Durable']",3,31,25,60,3430,1589,8474,4042,...,15328,7618,12075,6181,6405,3362,3320,1678,1301,710
3,Bloodseeker,"['Carry', 'Disabler', 'Jungler', 'Nuker', 'Ini...",4,72,25,55,12546,6456,17637,9090,...,17187,8788,10537,5306,4572,2391,1815,919,422,214
4,Crystal Maiden,"['Support', 'Disabler', 'Nuker', 'Jungler']",5,8,68,145,21576,11339,45844,23793,...,63042,31915,40881,20798,18614,9490,7608,3851,2117,1043

Mark if a hero is a traditional carry. We are only interested in viable carries.

In [7]:
df['is_carry'] = df['roles'].apply(lambda x: 'Carry' in x)
df = df.drop('roles', axis=1)

In [8]:
df.head()

,localized_name,hero_id,pro_ban,pro_win,pro_pick,1_pick,1_win,2_pick,2_win,3_pick,...,4_win,5_pick,5_win,6_pick,6_win,7_pick,7_win,8_pick,8_win,is_carry
0,Anti-Mage,1,429,56,115,19859,9964,44853,22780,64486,...,33598,44267,22427,20511,10160,8648,4249,2008,961,True
1,Axe,2,53,27,84,18628,9691,41356,21099,56903,...,27801,34984,17649,15361,7709,5965,2897,1211,591,False
2,Bane,3,31,25,60,3430,1589,8474,4042,13388,...,7618,12075,6181,6405,3362,3320,1678,1301,710,False
3,Bloodseeker,4,72,25,55,12546,6456,17637,9090,19542,...,8788,10537,5306,4572,2391,1815,919,422,214,True
4,Crystal Maiden,5,8,68,145,21576,11339,45844,23793,63059,...,31915,40881,20798,18614,9490,7608,3851,2117,1043,False

Separate columns based on extension. We can later subtract the columns for pro games from total for pub only stats. It seems that *x_pick* or *x_win* denotes the number of games for that pick. However, *9_pick,10_pick* and *9_win,10_win* are missing. But we can consider an average from this data as well.

In [9]:
cols_pick = [col for col in df.columns if col.endswith('_pick')]
cols_win = [col for col in df.columns if col.endswith('_win')]

In [10]:
cols_pick, cols_win

(['pro_pick',
  '1_pick',
  '2_pick',
  '3_pick',
  '4_pick',
  '5_pick',
  '6_pick',
  '7_pick',
  '8_pick'],
 ['pro_win',
  '1_win',
  '2_win',
  '3_win',
  '4_win',
  '5_win',
  '6_win',
  '7_win',
  '8_win'])

In [11]:
rows = df.to_dict('records')
total_picks = []
total_wins = []
for row in rows:
    total_pick = 0
    total_win = 0
    for field_pick, field_win in zip(cols_pick, cols_win):
        total_pick += row[field_pick]
        total_win += row[field_win]
    total_picks.append(total_pick)
    total_wins.append(total_win)

Calculate the stats. Note: we don't consider bans to be part of the hero win rate equation here. Also, since

In [12]:
df['pro_total'] = df['pro_pick']+df['pro_win']
df['pro_winrate'] = df['pro_win']/df['pro_total']
df['total_pick'] = total_picks
df['total_win'] = total_wins
df['pub_pick'] = df['total_pick']-df['pro_total']
df['pub_win'] = df['total_win']-df['pro_win']
df['pub_winrate'] = (df['pub_win']/df['pub_pick'])*100.0
df['pub_pickrate'] = df['pub_pick']/sum(df['pub_pick'])*100.0
df['pro_pickrate'] = df['pro_pick']/sum(df['pro_pick'])*100.0

In [13]:
df.head()

,localized_name,hero_id,pro_ban,pro_win,pro_pick,1_pick,1_win,2_pick,2_win,3_pick,...,is_carry,pro_total,pro_winrate,total_pick,total_win,pub_pick,pub_win,pub_winrate,pub_pickrate,pro_pickrate
0,Anti-Mage,1,429,56,115,19859,9964,44853,22780,64486,...,True,171,0.327485,270922,136977,270751,136921,50.570820,1.534320,0.802512
1,Axe,2,53,27,84,18628,9691,41356,21099,56903,...,False,111,0.243243,229193,116184,229082,116157,50.705424,1.298186,0.586183
2,Bane,3,31,25,60,3430,1589,8474,4042,13388,...,False,85,0.294118,63781,31688,63696,31663,49.709558,0.360959,0.418702
3,Bloodseeker,4,72,25,55,12546,6456,17637,9090,19542,...,True,80,0.312500,84313,43208,84233,43183,51.266131,0.477340,0.383810
4,Crystal Maiden,5,8,68,145,21576,11339,45844,23793,63059,...,False,213,0.319249,262886,134442,262673,134374,51.156381,1.488543,1.011863

In [14]:
df = df.drop(
    cols_pick,
    axis=1,
)
df = df.drop(
    cols_win,
    axis=1,
)

In [15]:
df.head()

,localized_name,hero_id,pro_ban,is_carry,pro_total,pro_winrate,total_pick,total_win,pub_pick,pub_win,pub_winrate,pub_pickrate,pro_pickrate
0,Anti-Mage,1,429,True,171,0.327485,270922,136977,270751,136921,50.570820,1.534320,0.802512
1,Axe,2,53,False,111,0.243243,229193,116184,229082,116157,50.705424,1.298186,0.586183
2,Bane,3,31,False,85,0.294118,63781,31688,63696,31663,49.709558,0.360959,0.418702
3,Bloodseeker,4,72,True,80,0.312500,84313,43208,84233,43183,51.266131,0.477340,0.383810
4,Crystal Maiden,5,8,False,213,0.319249,262886,134442,262673,134374,51.156381,1.488543,1.011863

In [16]:
df['pub_winrate'].describe()

count    120.000000
mean      49.747795
std        2.595116
min       42.175260
25%       48.457051
50%       49.842502
75%       51.372435
max       55.220532
Name: pub_winrate, dtype: float64

In [17]:
df['pub_pickrate'].describe()

count    120.000000
mean       0.833333
std        0.523581
min        0.060664
25%        0.452915
50%        0.691785
75%        1.078973
max        2.584273
Name: pub_pickrate, dtype: float64

Check heroes with more than 50% win rate

In [18]:
df[df['pub_winrate'] > 50.0].head()

,localized_name,hero_id,pro_ban,is_carry,pro_total,pro_winrate,total_pick,total_win,pub_pick,pub_win,pub_winrate,pub_pickrate,pro_pickrate
0,Anti-Mage,1,429,True,171,0.327485,270922,136977,270751,136921,50.570820,1.534320,0.802512
1,Axe,2,53,False,111,0.243243,229193,116184,229082,116157,50.705424,1.298186,0.586183
3,Bloodseeker,4,72,True,80,0.312500,84313,43208,84233,43183,51.266131,0.477340,0.383810
4,Crystal Maiden,5,8,False,213,0.319249,262886,134442,262673,134374,51.156381,1.488543,1.011863
7,Juggernaut,8,333,True,331,0.353474,383241,204838,382910,204721,53.464522,2.169915,1.493371

Check carry heroes with more than 50% win rate.

In [19]:
df[(df['pub_winrate'] > 50.0) & (df['is_carry'] == True)]

,localized_name,hero_id,pro_ban,is_carry,pro_total,pro_winrate,total_pick,total_win,pub_pick,pub_win,pub_winrate,pub_pickrate,pro_pickrate
0,Anti-Mage,1,429,True,171,0.327485,270922,136977,270751,136921,50.570820,1.534320,0.802512
3,Bloodseeker,4,72,True,80,0.312500,84313,43208,84233,43183,51.266131,0.477340,0.383810
7,Juggernaut,8,333,True,331,0.353474,383241,204838,382910,204721,53.464522,2.169915,1.493371
8,Mirana,9,145,True,447,0.340045,265730,138033,265283,137881,51.975061,1.503334,2.058618
14,Razor,15,23,True,31,0.290323,59035,31008,59004,30999,52.537116,0.334370,0.153524
20,Windranger,21,97,True,149,0.335570,318072,160839,317923,160789,50.574825,1.801640,0.690858
26,Slardar,28,342,True,295,0.315254,187336,94012,187041,93919,50.213055,1.059944,1.409630
30,Riki,32,167,True,176,0.312500,154098,83494,153922,83439,54.208625,0.872261,0.844382
34,Necrophos,36,22,True,33,0.363636,109082,54928,109049,54916,50.359013,0.617970,0.146546
40,Wraith King,42,201,True,335,0.340299,310292,170709,309957,170595,55.038280,1.756497,1.542219
46,Luna,48,11,True,39,0.333333,119849,60699,119810,60686,50.651865,0.678952,0.181438
47,Dragon Knight,49,42,True,63,0.269841,99827,51534,99764,51517,51.638868,0.565353,0.321005
54,Clinkz,56,48,True,37,0.297297,136379,73046,136342,73035,53.567499,0.772637,0.181438
58,Night Stalker,60,130,True,132,0.303030,89832,47275,89700,47235,52.658863,0.508321,0.642010
59,Broodmother,61,116,True,36,0.333333,28580,14605,28544,14593,51.124580,0.161756,0.167481
61,Weaver,63,87,True,143,0.321678,115784,58238,115641,58192,50.321253,0.655327,0.676902
65,Spectre,67,178,True,140,0.271429,203046,105325,202906,105287,51.889545,1.149849,0.711793
68,Ursa,70,292,True,258,0.313953,172628,88112,172370,88031,51.070952,0.976805,1.235171
69,Spirit Breaker,71,17,True,72,0.250000,170507,88006,170435,87988,51.625546,0.965839,0.376832
71,Alchemist,73,75,True,36,0.333333,89476,46810,89440,46798,52.323345,0.506848,0.167481
73,Silencer,75,41,True,43,0.209302,200516,102917,200473,102908,51.332598,1.136062,0.237264
75,Lycan,77,478,True,143,0.377622,52025,26551,51882,26497,51.071663,0.294010,0.621075
79,Chaos Knight,81,69,True,103,0.291262,112716,59004,112613,58974,52.368732,0.638167,0.509421
87,Naga Siren,89,85,True,42,0.333333,38793,19618,38751,19604,50.589662,0.219598,0.195394
92,Medusa,94,106,True,125,0.328000,111548,55821,111423,55780,50.061477,0.631424,0.586183
93,Troll Warlord,95,424,True,302,0.364238,145230,75379,144928,75269,51.935444,0.821293,1.339846
100,Abaddon,102,28,True,79,0.278481,73908,39491,73829,39469,53.460022,0.418382,0.397767
111,Arc Warden,113,145,True,73,0.328767,75949,40311,75876,40287,53.095841,0.429982,0.341940
112,Monkey King,114,347,True,356,0.376404,252477,133241,252121,133107,52.794888,1.428746,1.549197
117,Void Spirit,126,440,True,508,0.336614,126559,63621,126051,63450,50.336768,0.714319,2.351710

Check carry heroes with more than 50% win rate and at least 10% pick rate. This goes to show that our data source is not reliable. So if anyone has a better idea where to take data for checking hero winrates, feel free to share with me.

In [20]:
df[(df['pub_winrate'] > 50.0) & (df['pub_pickrate'] >= 10.0) & (df['is_carry'] == True)].shape[0]

0